<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AutoDuck.Helper</AssemblyName>
    <RootNamespace>AutoDuck.Helper</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <!-- Wrapper WASAPI / Core Audio API (IAudioSessionManager2, IAudioSessionEvents, IMMNotificationClient) -->
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
